### ISSUE TITLE
Shouldn't newHeap() return a "ref Heap"?

### ISSUE THREAD

**Issue by cdunn2001** [bluenote10/nim-heap#4]
I guess this was written for an older version of Nim. Or maybe I have misunderstood the recommended conventions. I'm still fairly new to Nim.

**Comment by bluenote10** [comment]
My take on it was that having two constructors like `initTable` + `newTable` is only common if there is a ref and a non-version explicitly defined. Since there is currently only a non-ref version, I just went for the most natural name to produce a new head. Would you prefer `initHeap`?

**Comment by cdunn2001** [comment]
I don't have an opinion. I was hoping you understood the conventions better than a newbie like me would. I'm fine with whatever you think is best. Thanks for the library.
